# Generated by Django 3.0.2 on 2020-05-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unitconverterapp', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='conversion',
            constraint=models.UniqueConstraint(fields=('from_unit', 'to_unit'), name='uniq_from_to_units'),
        ),
    ]
