# Generated by Django 3.0.2 on 2020-05-10 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unitconverterapp', '0002_auto_20200510_1830'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='conversion',
            constraint=models.UniqueConstraint(fields=('name',), name='uniq_converter_name'),
        ),
    ]
