# Generated by Django 3.1.1 on 2020-11-14 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unitconverterapp', '0003_auto_20200510_1833'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='UnitConvertType',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='category',
            new_name='unit_convert_type',
        ),
    ]
