# Generated by Django 3.1.1 on 2020-11-14 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unitconverterapp', '0004_auto_20201114_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='wiki_link',
        ),
    ]
