# Generated by Django 3.1.1 on 2020-11-15 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unitconverterapp', '0005_remove_unit_wiki_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
