# Generated by Django 3.1.1 on 2020-11-23 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unitconverterapp', '0007_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_description', models.TextField()),
                ('measurement_title', models.CharField(blank=True, max_length=100, null=True)),
                ('measurement_article_link', models.URLField(blank=True, null=True)),
                ('measurement_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurement_name', to='unitconverterapp.measurement')),
            ],
        ),
        migrations.CreateModel(
            name='UnitArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_description', models.TextField()),
                ('unit_title', models.CharField(blank=True, max_length=100, null=True)),
                ('unit_article_link', models.URLField(blank=True, null=True)),
                ('unit_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_name', to='unitconverterapp.unit')),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
