# Generated by Django 3.1.1 on 2020-11-24 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unitconverterapp', '0008_auto_20201123_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurementarticle',
            name='measurement_img',
            field=models.ImageField(blank=True, null=True, upload_to='measurement'),
        ),
        migrations.AlterField(
            model_name='unitarticle',
            name='unit_img',
            field=models.ImageField(blank=True, null=True, upload_to='unit'),
        ),
    ]
