# Generated by Django 3.1.1 on 2020-11-24 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unitconverterapp', '0010_auto_20201124_0657'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='unitarticle',
            name='unit',
        ),
        migrations.AddField(
            model_name='unitarticle',
            name='unit_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit_name', to='unitconverterapp.unittype'),
        ),
    ]
